In [1]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [2]:
dataFolder = 'input/'
dataFile = dataFolder + "iris.csv"
print(dataFile)

input/iris.csv


In [3]:
df = pd.read_csv(dataFile)
df.head()

sepal length (cm)   sepal width (cm)   petal length (cm)  \
0                5.1                3.5                 1.4   
1                4.9                3.0                 1.4   
2                4.7                3.2                 1.3   
3                4.6                3.1                 1.5   
4                5.0                3.6                 1.4   

    petal width (cm)        class  
0                0.2  Iris-setosa  
1                0.2  Iris-setosa  
2                0.2  Iris-setosa  
3                0.2  Iris-setosa  
4                0.2  Iris-setosa

In [4]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [5]:
print(X[0:5])
print(y[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [6]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [7]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [8]:
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [11]:
print(X_train[0:5])

[[6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]]


In [12]:
print(y_train[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]]


In [13]:
print(X_test[0:5])

[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]]


In [14]:
print(y_test[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]]


In [15]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='sigmoid'),
    tf.keras.layers.Dense(10, activation='sigmoid'),
    tf.keras.layers.Dense(3, activation='sigmoid')
  ])
model

In [16]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [17]:
model.fit(X_train, y_train, batch_size=50, epochs=100)


Epoch 1/100
3/3 [==============================] - 1s 4ms/step - loss: 1.1225 - accuracy: 0.0417
Epoch 2/100
3/3 [==============================] - 0s 2ms/step - loss: 1.1114 - accuracy: 0.0250
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 1.1056 - accuracy: 0.0417
Epoch 4/100
3/3 [==============================] - 0s 3ms/step - loss: 1.1015 - accuracy: 0.0000e+00
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 1.0983 - accuracy: 0.0083
Epoch 6/100
3/3 [==============================] - 0s 2ms/step - loss: 1.0954 - accuracy: 0.0417
Epoch 7/100
3/3 [==============================] - 0s 2ms/step - loss: 1.0935 - accuracy: 0.3667
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 1.0918 - accuracy: 0.4000
Epoch 9/100
3/3 [==============================] - 0s 3ms/step - loss: 1.0894 - accuracy: 0.3667
Epoch 10/100
3/3 [==============================] - 0s 2ms/step - loss: 1.0876 - accuracy: 0.3667
Epoch 11/100
3/3 [=======

In [18]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.9385626912117004
Test accuracy: 0.5666666626930237


In [19]:
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 170ms/step


array([[0.46898198, 0.48630634, 0.63611573],
       [0.5404116 , 0.54841155, 0.5644875 ],
       [0.68299   , 0.6108615 , 0.44877136],
       [0.46694887, 0.50197506, 0.6253562 ],
       [0.6732965 , 0.607275  , 0.45700264],
       [0.4566115 , 0.47885415, 0.6462766 ],
       [0.6768023 , 0.6072052 , 0.45505148],
       [0.5201994 , 0.52950615, 0.5846566 ],
       [0.51626885, 0.5321534 , 0.5849998 ],
       [0.5420453 , 0.5409659 , 0.56752527],
       [0.47739822, 0.50607246, 0.61930144],
       [0.52498436, 0.52851766, 0.5830547 ],
       [0.5141941 , 0.5277627 , 0.5890199 ],
       [0.51594937, 0.52814347, 0.58781034],
       [0.5094391 , 0.5217158 , 0.5949995 ],
       [0.67820656, 0.6087594 , 0.45345658],
       [0.5127674 , 0.5212843 , 0.5937878 ],
       [0.5132717 , 0.5237342 , 0.5925135 ],
       [0.6694001 , 0.60525805, 0.4607619 ],
       [0.6794914 , 0.6079218 , 0.4526402 ],
       [0.47949687, 0.49491572, 0.6260677 ],
       [0.5076978 , 0.51435304, 0.60072386],
       [0.

In [20]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Predicted: [2 2 0 2 0 2 0 2 2 2 2 2 2 2 2 0 2 2 0 0 2 2 0 0 2 0 0 2 2 0]
